/* ============================================================
   Economat - Tables de facturation dediees
   A executer dans la base ECONOMAT (SQL Server / SSMS).
   Multi-tenant : CODESOCIETE + CODEETABLISSEMENT + ANNEE.
   Les lignes peuvent referencer une categorie de l'echeancier
   (T_CATEGORIEPAIEMENT) via CODE_CATEGORIE.
   ============================================================ */

USE [Economat];
GO

IF OBJECT_ID('dbo.ECO_FACTURE', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.ECO_FACTURE (
        ID             INT IDENTITY(1,1) NOT NULL,
        NUMERO         VARCHAR(50)    NOT NULL,
        MATRICULE      VARCHAR(50)    NOT NULL,
        ANNEE          VARCHAR(20)    NULL,
        DATE_EMISSION  DATE           NOT NULL,
        DATE_ECHEANCE  DATE           NULL,
        MONTANT_TOTAL  DECIMAL(18,2)  NOT NULL CONSTRAINT DF_ECO_FACT_TOTAL DEFAULT (0),
        MONTANT_PAYE   DECIMAL(18,2)  NOT NULL CONSTRAINT DF_ECO_FACT_PAYE DEFAULT (0),
        STATUT         VARCHAR(20)    NULL CONSTRAINT DF_ECO_FACT_STATUT DEFAULT ('impayee'),
        NOTES          NVARCHAR(1000) NULL,
        CODEETABLISSEMENT NVARCHAR(50) NULL,
        CODESOCIETE    VARCHAR(50)    NULL,
        CREATED_AT     DATETIME       NULL CONSTRAINT DF_ECO_FACT_CREATED DEFAULT (GETDATE()),
        CONSTRAINT PK_ECO_FACTURE PRIMARY KEY CLUSTERED (ID)
    );
    CREATE INDEX IX_ECO_FACT_TENANT ON dbo.ECO_FACTURE (CODESOCIETE, CODEETABLISSEMENT, ANNEE);
    CREATE INDEX IX_ECO_FACT_MAT    ON dbo.ECO_FACTURE (MATRICULE);
END
GO

IF OBJECT_ID('dbo.ECO_FACTURE_LIGNE', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.ECO_FACTURE_LIGNE (
        ID             INT IDENTITY(1,1) NOT NULL,
        FACTURE_ID     INT            NOT NULL,
        LIBELLE        NVARCHAR(255)  NOT NULL,
        MONTANT        DECIMAL(18,2)  NOT NULL CONSTRAINT DF_ECO_FLIGNE_MONTANT DEFAULT (0),
        CODE_CATEGORIE VARCHAR(50)    NULL,
        CREATED_AT     DATETIME       NULL CONSTRAINT DF_ECO_FLIGNE_CREATED DEFAULT (GETDATE()),
        CONSTRAINT PK_ECO_FACTURE_LIGNE PRIMARY KEY CLUSTERED (ID),
        CONSTRAINT FK_ECO_FLIGNE_FACT FOREIGN KEY (FACTURE_ID) REFERENCES dbo.ECO_FACTURE (ID) ON DELETE CASCADE
    );
    CREATE INDEX IX_ECO_FLIGNE_FACT ON dbo.ECO_FACTURE_LIGNE (FACTURE_ID);
END
GO
