/* Economat - Modalités de paiement paramétrables. A exécuter sur la base ECONOMAT. */
USE [Economat];
GO
IF OBJECT_ID('dbo.ECO_MODE_PAIEMENT', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.ECO_MODE_PAIEMENT (
        ID INT IDENTITY(1,1) NOT NULL,
        LIBELLE NVARCHAR(80) NOT NULL,
        CODESOCIETE VARCHAR(50) NULL,
        CODEETABLISSEMENT NVARCHAR(50) NULL,
        ACTIF BIT NOT NULL CONSTRAINT DF_ECO_MODE_ACTIF DEFAULT (1),
        CREATED_AT DATETIME NULL CONSTRAINT DF_ECO_MODE_CREATED DEFAULT (GETDATE()),
        CONSTRAINT PK_ECO_MODE_PAIEMENT PRIMARY KEY CLUSTERED (ID)
    );
    CREATE INDEX IX_ECO_MODE_TENANT ON dbo.ECO_MODE_PAIEMENT (CODESOCIETE, CODEETABLISSEMENT);
END
GO
