/* Economat - Affectation caisse <-> utilisateur caissier. A executer sur ECONOMAT. */
USE [Economat];
GO
IF OBJECT_ID('dbo.ECO_USER_CAISSE', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.ECO_USER_CAISSE (
        ID INT IDENTITY(1,1) NOT NULL,
        USER_ID INT NOT NULL,
        CODECAISSE VARCHAR(50) NOT NULL,
        CODESOCIETE VARCHAR(50) NULL,
        CODEETABLISSEMENT NVARCHAR(50) NULL,
        CREATED_AT DATETIME NULL CONSTRAINT DF_ECO_USER_CAISSE_CREATED DEFAULT (GETDATE()),
        CONSTRAINT PK_ECO_USER_CAISSE PRIMARY KEY CLUSTERED (ID)
    );
    CREATE INDEX IX_ECO_USER_CAISSE_USER ON dbo.ECO_USER_CAISSE (USER_ID);
END
GO
